plugins:
  - redcarpet
  - rouge

title: Hugo Lundin
permalink: :title
baseurl: /
name: Hugo Lundin
description: Programmer and computer engineering student.
url: https://hugolundin.se

plugins:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
