plugins:
  - redcarpet
  - rouge

permalink: pretty
baseurl: /

title: Hugo Lundin
url: https://www.hugolundin.se
description: Software developer.

links:
  - title: Github
    url: https://www.github.com/hugolundin
  
  - title: Email
    url: mailto:contact@hugolundin.se

  - title: Spotify
    url: https://open.spotify.com/user/hugolundin?si=fU8_4QprTqC1SJt2L1pakQ

  - title: Resume
    url: https://www.hugolundin.se/files/resume.pdf

  - title: Instagram
    url: https://www.instagram.com/hugolundin

  
