plugins:
  - redcarpet
  - rouge

title: Hugo Lundin
permalink: https://hugolundin.se
baseurl: https://hugolundin.se
name: Hugo Lundin
description: Programmer and computer engineering student.
url: https://hugolundin.se

plugins:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
